// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyO4G7l24ADPT-VCOcBUCBpQ1z9O-0T5U',
    appId: '1:244926327377:web:914373170246c8a103a670',
    messagingSenderId: '244926327377',
    projectId: 'maternal-healthcare-app-20c2c',
    authDomain: 'maternal-healthcare-app-20c2c.firebaseapp.com',
    storageBucket: 'maternal-healthcare-app-20c2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi7FTwxvNWmfHcYoxmY392QOSthmdCNFE',
    appId: '1:244926327377:android:d0c9d052702bdfa303a670',
    messagingSenderId: '244926327377',
    projectId: 'maternal-healthcare-app-20c2c',
    storageBucket: 'maternal-healthcare-app-20c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAscwQfKc9KiTLx1vx6nLxpA9o4-xMRTpw',
    appId: '1:244926327377:ios:4818695cdd65a33603a670',
    messagingSenderId: '244926327377',
    projectId: 'maternal-healthcare-app-20c2c',
    storageBucket: 'maternal-healthcare-app-20c2c.firebasestorage.app',
    iosBundleId: 'com.example.maternalhealthcare',
  );

}